<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount">
        <div class="border-bottom">
        <h4><?php echo $this->__('Discount Codes') ?></h4>
        </div>
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
        <div class="row">
        <div class="large-12 columns">
          <div class="row collapse">
            <div class="small-10 columns">
              <input type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
            </div>
            <div class="small-2 columns">
               <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button coupon" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><?php echo $this->__('Apply') ?></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button coupon" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
                <?php endif;?>
                
            </div>
          </div>
        </div>
      </div>

    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>